version: "3.9"

services:
  backend:
    build: .
    container_name: rapiti_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    restart: always

  database:
    image: postgres:15
    container_name: rapiti_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rapiti_db
      POSTGRES_USER: rapiti_user
      POSTGRES_PASSWORD: rapiti_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
